# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:EnvironmentName=Development /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(solution)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure for Students(e0a01be8-bdd1-4e00-bd3f-ee558f97e070)'
    appType: 'webApp'
    WebAppName: 'PublicBoard-WebApp-DEV'
    packageForLinux: "$(build.artifactStagingDirectory)/**/*.zip"

- task: AzureCLI@2
  displayName: "Set Environemt Varaibles"
  inputs:
    azureSubscription: 'Azure for Students(e0a01be8-bdd1-4e00-bd3f-ee558f97e070)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'az webapp appsettings set --name "PublicBoard-WebApp-DEV" --setting-names "ASPNETCORE_ALLOWED_ORIGINS=https://calm-glacier-0db670103.2.azurestaticapps.net"'